//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AI_Anomaly_Category
    {
        public int id { get; set; }
        public Nullable<int> branch_id { get; set; }
        public Nullable<int> category_id { get; set; }
        public Nullable<System.DateTime> period_start { get; set; }
        public Nullable<System.DateTime> period_end { get; set; }
        public Nullable<int> actual_qty { get; set; }
        public Nullable<int> forecast_qty { get; set; }
        public Nullable<decimal> deviation_percent { get; set; }
        public string anomaly_type { get; set; }
        public string severity { get; set; }
        public Nullable<System.DateTime> detected_at { get; set; }
    }
}
