//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AI_ChatLog
    {
        public long Id { get; set; }
        public string SessionId { get; set; }
        public string Role { get; set; }
        public string Content { get; set; }
        public Nullable<int> TokenCount { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    }
}
