//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AI_InventoryWarning
    {
        public int id { get; set; }
        public Nullable<int> branch_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<int> current_stock { get; set; }
        public Nullable<int> days_to_exhaust { get; set; }
        public string warning_type { get; set; }
        public Nullable<decimal> confidence_score { get; set; }
        public string risk_reason { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    }
}
