//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AI_Purchase_Recommendation
    {
        public int id { get; set; }
        public Nullable<int> branch_id { get; set; }
        public Nullable<int> warehouse_id { get; set; }
        public Nullable<int> category_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<System.DateTime> period_start { get; set; }
        public Nullable<System.DateTime> period_end { get; set; }
        public Nullable<int> forecast_demand { get; set; }
        public Nullable<int> current_stock { get; set; }
        public Nullable<int> recommended_min { get; set; }
        public Nullable<int> recommended_max { get; set; }
        public string reason { get; set; }
        public string confidence_level { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    }
}
