//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AI_Product_Insight
    {
        public int id { get; set; }
        public Nullable<int> branch_id { get; set; }
        public Nullable<int> category_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<System.DateTime> period_start { get; set; }
        public Nullable<System.DateTime> period_end { get; set; }
        public Nullable<int> qty_sold { get; set; }
        public Nullable<int> baseline_qty { get; set; }
        public Nullable<decimal> growth_percent { get; set; }
        public Nullable<decimal> contribution_percent { get; set; }
        public string insight_level { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    }
}
