//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AI_Training_Data
    {
        public int id { get; set; }
        public Nullable<int> branch_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<System.DateTime> sale_date { get; set; }
        public Nullable<int> qty { get; set; }
        public Nullable<int> category_id { get; set; }
    }
}
