//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppLog
    {
        public long log_id { get; set; }
        public string thread { get; set; }
        public string log_level { get; set; }
        public string logger { get; set; }
        public string message { get; set; }
        public string exception { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    }
}
