//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLog
    {
        public long audit_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string table_name { get; set; }
        public string primary_key_id { get; set; }
        public string action_type { get; set; }
        public string old_values { get; set; }
        public string new_values { get; set; }
        public string ip_address { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    
        public virtual User User { get; set; }
    }
}
