//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMarket.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EMarket_DBEntities : DbContext
    {
        public EMarket_DBEntities()
            : base("name=EMarket_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Branch> Branches { get; set; }
        public virtual DbSet<CustomerAddress> CustomerAddresses { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<LoyaltyProgram> LoyaltyPrograms { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
        public virtual DbSet<ProductCategory> ProductCategories { get; set; }
        public virtual DbSet<ProductImage> ProductImages { get; set; }
        public virtual DbSet<ProductLot> ProductLots { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Promotion> Promotions { get; set; }
        public virtual DbSet<PurchaseOrderDetail> PurchaseOrderDetails { get; set; }
        public virtual DbSet<PurchaseOrder> PurchaseOrders { get; set; }
        public virtual DbSet<ReportDetail> ReportDetails { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
        public virtual DbSet<RolePermission> RolePermissions { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<StockMovement> StockMovements { get; set; }
        public virtual DbSet<SupplierDebt> SupplierDebts { get; set; }
        public virtual DbSet<SupplierPayment> SupplierPayments { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Warehouse> Warehouses { get; set; }
        public virtual DbSet<SystemConfig> SystemConfigs { get; set; }
        public virtual DbSet<AggregatedCounter> AggregatedCounters { get; set; }
        public virtual DbSet<Counter> Counters { get; set; }
        public virtual DbSet<Hash> Hashes { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<JobParameter> JobParameters { get; set; }
        public virtual DbSet<JobQueue> JobQueues { get; set; }
        public virtual DbSet<List> Lists { get; set; }
        public virtual DbSet<Schema> Schemata { get; set; }
        public virtual DbSet<Server> Servers { get; set; }
        public virtual DbSet<Set> Sets { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<AI_Anomaly_Category> AI_Anomaly_Category { get; set; }
        public virtual DbSet<AI_Product_Insight> AI_Product_Insight { get; set; }
        public virtual DbSet<AI_Purchase_Recommendation> AI_Purchase_Recommendation { get; set; }
        public virtual DbSet<AI_ReplenishmentAdvice> AI_ReplenishmentAdvice { get; set; }
        public virtual DbSet<AI_Training_Data> AI_Training_Data { get; set; }
        public virtual DbSet<ExpenseCategory> ExpenseCategories { get; set; }
        public virtual DbSet<Expens> Expenses { get; set; }
        public virtual DbSet<QuotationDetail> QuotationDetails { get; set; }
        public virtual DbSet<Quotation> Quotations { get; set; }
        public virtual DbSet<AppLog> AppLogs { get; set; }
        public virtual DbSet<AuditLog> AuditLogs { get; set; }
        public virtual DbSet<ForgotPasswordOtp> ForgotPasswordOtps { get; set; }
        public virtual DbSet<Inventory> Inventories { get; set; }
        public virtual DbSet<AI_ChatLog> AI_ChatLog { get; set; }
        public virtual DbSet<AI_InventoryWarning> AI_InventoryWarning { get; set; }
        public virtual DbSet<AI_SalesForecast> AI_SalesForecast { get; set; }
        public virtual DbSet<v_AI_Customer_Analytics> v_AI_Customer_Analytics { get; set; }
        public virtual DbSet<v_AI_Master_Input> v_AI_Master_Input { get; set; }
        public virtual DbSet<v_AI_Master_Input_XGB> v_AI_Master_Input_XGB { get; set; }
        public virtual DbSet<v_WeeklySales_ByProduct> v_WeeklySales_ByProduct { get; set; }
    
        public virtual int sp_Admin_Dashboard_BranchPerformance(Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate, Nullable<int> branchId)
        {
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            var branchIdParameter = branchId.HasValue ?
                new ObjectParameter("BranchId", branchId) :
                new ObjectParameter("BranchId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Admin_Dashboard_BranchPerformance", fromDateParameter, toDateParameter, branchIdParameter);
        }
    
        public virtual ObjectResult<sp_Admin_Dashboard_Overview_Result> sp_Admin_Dashboard_Overview(Nullable<int> branchId, Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate, string groupBy)
        {
            var branchIdParameter = branchId.HasValue ?
                new ObjectParameter("BranchId", branchId) :
                new ObjectParameter("BranchId", typeof(int));
    
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            var groupByParameter = groupBy != null ?
                new ObjectParameter("GroupBy", groupBy) :
                new ObjectParameter("GroupBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Admin_Dashboard_Overview_Result>("sp_Admin_Dashboard_Overview", branchIdParameter, fromDateParameter, toDateParameter, groupByParameter);
        }
    
        public virtual int sp_Admin_Dashboard_StockChart(Nullable<int> branchId)
        {
            var branchIdParameter = branchId.HasValue ?
                new ObjectParameter("BranchId", branchId) :
                new ObjectParameter("BranchId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Admin_Dashboard_StockChart", branchIdParameter);
        }
    
        public virtual int sp_Admin_Dashboard_Summary(Nullable<int> branchId)
        {
            var branchIdParameter = branchId.HasValue ?
                new ObjectParameter("BranchId", branchId) :
                new ObjectParameter("BranchId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Admin_Dashboard_Summary", branchIdParameter);
        }
    
        public virtual int sp_AI_Analyze_Anomalies(Nullable<int> targetBranchId, Nullable<System.DateTime> analysisDate)
        {
            var targetBranchIdParameter = targetBranchId.HasValue ?
                new ObjectParameter("TargetBranchId", targetBranchId) :
                new ObjectParameter("TargetBranchId", typeof(int));
    
            var analysisDateParameter = analysisDate.HasValue ?
                new ObjectParameter("AnalysisDate", analysisDate) :
                new ObjectParameter("AnalysisDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_AI_Analyze_Anomalies", targetBranchIdParameter, analysisDateParameter);
        }
    
        public virtual int sp_AI_Analyze_ProductInsights(Nullable<int> targetBranchId, Nullable<System.DateTime> analysisDate)
        {
            var targetBranchIdParameter = targetBranchId.HasValue ?
                new ObjectParameter("TargetBranchId", targetBranchId) :
                new ObjectParameter("TargetBranchId", typeof(int));
    
            var analysisDateParameter = analysisDate.HasValue ?
                new ObjectParameter("AnalysisDate", analysisDate) :
                new ObjectParameter("AnalysisDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_AI_Analyze_ProductInsights", targetBranchIdParameter, analysisDateParameter);
        }
    
        public virtual int sp_AI_Analyze_Purchasing(Nullable<int> targetBranchId, Nullable<System.DateTime> analysisDate)
        {
            var targetBranchIdParameter = targetBranchId.HasValue ?
                new ObjectParameter("TargetBranchId", targetBranchId) :
                new ObjectParameter("TargetBranchId", typeof(int));
    
            var analysisDateParameter = analysisDate.HasValue ?
                new ObjectParameter("AnalysisDate", analysisDate) :
                new ObjectParameter("AnalysisDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_AI_Analyze_Purchasing", targetBranchIdParameter, analysisDateParameter);
        }
    
        public virtual int sp_AI_Refresh_Training_Data()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_AI_Refresh_Training_Data");
        }
    
        public virtual int sp_AI_Run_Full_Analysis(Nullable<int> targetBranchId)
        {
            var targetBranchIdParameter = targetBranchId.HasValue ?
                new ObjectParameter("TargetBranchId", targetBranchId) :
                new ObjectParameter("TargetBranchId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_AI_Run_Full_Analysis", targetBranchIdParameter);
        }
    
        public virtual ObjectResult<sp_Finance_GetDashboardData_Result> sp_Finance_GetDashboardData(Nullable<int> daysBack, Nullable<int> branchId)
        {
            var daysBackParameter = daysBack.HasValue ?
                new ObjectParameter("DaysBack", daysBack) :
                new ObjectParameter("DaysBack", typeof(int));
    
            var branchIdParameter = branchId.HasValue ?
                new ObjectParameter("BranchId", branchId) :
                new ObjectParameter("BranchId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Finance_GetDashboardData_Result>("sp_Finance_GetDashboardData", daysBackParameter, branchIdParameter);
        }
    
        public virtual int sp_GetSuperAdminHubData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_GetSuperAdminHubData");
        }
    
        public virtual ObjectResult<sp_GetSupplierDebtDashboard_Result> sp_GetSupplierDebtDashboard(Nullable<int> branchId, Nullable<int> supplierId, Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate)
        {
            var branchIdParameter = branchId.HasValue ?
                new ObjectParameter("BranchId", branchId) :
                new ObjectParameter("BranchId", typeof(int));
    
            var supplierIdParameter = supplierId.HasValue ?
                new ObjectParameter("SupplierId", supplierId) :
                new ObjectParameter("SupplierId", typeof(int));
    
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetSupplierDebtDashboard_Result>("sp_GetSupplierDebtDashboard", branchIdParameter, supplierIdParameter, fromDateParameter, toDateParameter);
        }
    
        public virtual ObjectResult<sp_PeopleDashboard_Charts_Result> sp_PeopleDashboard_Charts()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_PeopleDashboard_Charts_Result>("sp_PeopleDashboard_Charts");
        }
    
        public virtual ObjectResult<sp_PeopleDashboard_KPI_Result> sp_PeopleDashboard_KPI()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_PeopleDashboard_KPI_Result>("sp_PeopleDashboard_KPI");
        }
    
        public virtual int sp_Quotation_ConvertToOrder(Nullable<int> quotation_id, Nullable<int> user_id, string payment_method)
        {
            var quotation_idParameter = quotation_id.HasValue ?
                new ObjectParameter("quotation_id", quotation_id) :
                new ObjectParameter("quotation_id", typeof(int));
    
            var user_idParameter = user_id.HasValue ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(int));
    
            var payment_methodParameter = payment_method != null ?
                new ObjectParameter("payment_method", payment_method) :
                new ObjectParameter("payment_method", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Quotation_ConvertToOrder", quotation_idParameter, user_idParameter, payment_methodParameter);
        }
    
        public virtual int sp_Sales_Checkout(Nullable<int> branch_id, Nullable<int> user_id, Nullable<int> customer_id, Nullable<decimal> total_amount, Nullable<int> points_redeemed, string status, Nullable<int> points_earned, Nullable<decimal> manual_discount, string discount_reason, Nullable<int> parent_order_id, string payment_method)
        {
            var branch_idParameter = branch_id.HasValue ?
                new ObjectParameter("branch_id", branch_id) :
                new ObjectParameter("branch_id", typeof(int));
    
            var user_idParameter = user_id.HasValue ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(int));
    
            var customer_idParameter = customer_id.HasValue ?
                new ObjectParameter("customer_id", customer_id) :
                new ObjectParameter("customer_id", typeof(int));
    
            var total_amountParameter = total_amount.HasValue ?
                new ObjectParameter("total_amount", total_amount) :
                new ObjectParameter("total_amount", typeof(decimal));
    
            var points_redeemedParameter = points_redeemed.HasValue ?
                new ObjectParameter("points_redeemed", points_redeemed) :
                new ObjectParameter("points_redeemed", typeof(int));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            var points_earnedParameter = points_earned.HasValue ?
                new ObjectParameter("points_earned", points_earned) :
                new ObjectParameter("points_earned", typeof(int));
    
            var manual_discountParameter = manual_discount.HasValue ?
                new ObjectParameter("manual_discount", manual_discount) :
                new ObjectParameter("manual_discount", typeof(decimal));
    
            var discount_reasonParameter = discount_reason != null ?
                new ObjectParameter("discount_reason", discount_reason) :
                new ObjectParameter("discount_reason", typeof(string));
    
            var parent_order_idParameter = parent_order_id.HasValue ?
                new ObjectParameter("parent_order_id", parent_order_id) :
                new ObjectParameter("parent_order_id", typeof(int));
    
            var payment_methodParameter = payment_method != null ?
                new ObjectParameter("payment_method", payment_method) :
                new ObjectParameter("payment_method", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Sales_Checkout", branch_idParameter, user_idParameter, customer_idParameter, total_amountParameter, points_redeemedParameter, statusParameter, points_earnedParameter, manual_discountParameter, discount_reasonParameter, parent_order_idParameter, payment_methodParameter);
        }
    
        public virtual int sp_Sales_Checkout_Core(Nullable<int> branch_id, Nullable<int> user_id, Nullable<int> customer_id, Nullable<decimal> total_amount, Nullable<int> points_redeemed, string status, Nullable<int> points_earned, Nullable<decimal> manual_discount, string discount_reason, Nullable<int> parent_order_id, string payment_method, ObjectParameter new_order_id)
        {
            var branch_idParameter = branch_id.HasValue ?
                new ObjectParameter("branch_id", branch_id) :
                new ObjectParameter("branch_id", typeof(int));
    
            var user_idParameter = user_id.HasValue ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(int));
    
            var customer_idParameter = customer_id.HasValue ?
                new ObjectParameter("customer_id", customer_id) :
                new ObjectParameter("customer_id", typeof(int));
    
            var total_amountParameter = total_amount.HasValue ?
                new ObjectParameter("total_amount", total_amount) :
                new ObjectParameter("total_amount", typeof(decimal));
    
            var points_redeemedParameter = points_redeemed.HasValue ?
                new ObjectParameter("points_redeemed", points_redeemed) :
                new ObjectParameter("points_redeemed", typeof(int));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            var points_earnedParameter = points_earned.HasValue ?
                new ObjectParameter("points_earned", points_earned) :
                new ObjectParameter("points_earned", typeof(int));
    
            var manual_discountParameter = manual_discount.HasValue ?
                new ObjectParameter("manual_discount", manual_discount) :
                new ObjectParameter("manual_discount", typeof(decimal));
    
            var discount_reasonParameter = discount_reason != null ?
                new ObjectParameter("discount_reason", discount_reason) :
                new ObjectParameter("discount_reason", typeof(string));
    
            var parent_order_idParameter = parent_order_id.HasValue ?
                new ObjectParameter("parent_order_id", parent_order_id) :
                new ObjectParameter("parent_order_id", typeof(int));
    
            var payment_methodParameter = payment_method != null ?
                new ObjectParameter("payment_method", payment_method) :
                new ObjectParameter("payment_method", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Sales_Checkout_Core", branch_idParameter, user_idParameter, customer_idParameter, total_amountParameter, points_redeemedParameter, statusParameter, points_earnedParameter, manual_discountParameter, discount_reasonParameter, parent_order_idParameter, payment_methodParameter, new_order_id);
        }
    
        public virtual int sp_Warehouse_GetDashboardData(Nullable<int> daysBack, Nullable<int> branchId, Nullable<int> warehouseId)
        {
            var daysBackParameter = daysBack.HasValue ?
                new ObjectParameter("DaysBack", daysBack) :
                new ObjectParameter("DaysBack", typeof(int));
    
            var branchIdParameter = branchId.HasValue ?
                new ObjectParameter("BranchId", branchId) :
                new ObjectParameter("BranchId", typeof(int));
    
            var warehouseIdParameter = warehouseId.HasValue ?
                new ObjectParameter("WarehouseId", warehouseId) :
                new ObjectParameter("WarehouseId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Warehouse_GetDashboardData", daysBackParameter, branchIdParameter, warehouseIdParameter);
        }
    }
}
