//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expens
    {
        public int expense_id { get; set; }
        public int branch_id { get; set; }
        public int category_id { get; set; }
        public int user_id { get; set; }
        public decimal amount { get; set; }
        public Nullable<System.DateTime> expense_date { get; set; }
        public string note { get; set; }
        public string ref_image { get; set; }
        public string payment_method { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<int> approved_by { get; set; }
        public Nullable<System.DateTime> approved_at { get; set; }
        public Nullable<int> rejected_by { get; set; }
        public Nullable<System.DateTime> rejected_at { get; set; }
        public string reject_reason { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual ExpenseCategory ExpenseCategory { get; set; }
        public virtual User User { get; set; }
    }
}
