//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public int inventory_id { get; set; }
        public int warehouse_id { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<System.DateTime> last_update { get; set; }
        public int lot_id { get; set; }
    
        public virtual Warehouse Warehouse { get; set; }
        public virtual ProductLot ProductLot { get; set; }
    }
}
