//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoyaltyProgram
    {
        public int loyalty_id { get; set; }
        public int customer_id { get; set; }
        public Nullable<int> order_id { get; set; }
        public Nullable<int> points_earned { get; set; }
        public Nullable<int> points_redeemed { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Order Order { get; set; }
    }
}
