//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promotion
    {
        public int promotion_id { get; set; }
        public string name { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime end_date { get; set; }
        public string discount_type { get; set; }
        public Nullable<decimal> discount_value { get; set; }
        public Nullable<int> category_id { get; set; }
        public string customer_type { get; set; }
        public Nullable<int> priority { get; set; }
        public Nullable<bool> is_active { get; set; }
    
        public virtual ProductCategory ProductCategory { get; set; }
    }
}
