//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderDetail
    {
        public int purchase_order_detail_id { get; set; }
        public int purchase_order_id { get; set; }
        public int product_id { get; set; }
        public int category_id { get; set; }
        public int quantity { get; set; }
        public Nullable<decimal> unit_price { get; set; }
        public Nullable<decimal> total_price { get; set; }
        public Nullable<int> lot_id { get; set; }
    
        public virtual ProductCategory ProductCategory { get; set; }
        public virtual Product Product { get; set; }
        public virtual PurchaseOrder PurchaseOrder { get; set; }
        public virtual ProductLot ProductLot { get; set; }
    }
}
