//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quotation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Quotation()
        {
            this.QuotationDetails = new HashSet<QuotationDetail>();
        }
    
        public int quotation_id { get; set; }
        public string quotation_code { get; set; }
        public int branch_id { get; set; }
        public Nullable<int> customer_id { get; set; }
        public int user_id { get; set; }
        public decimal total_amount { get; set; }
        public Nullable<decimal> discount_amount { get; set; }
        public decimal final_amount { get; set; }
        public Nullable<System.DateTime> issue_date { get; set; }
        public System.DateTime expiry_date { get; set; }
        public string status { get; set; }
        public string note { get; set; }
        public Nullable<int> converted_order_id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<decimal> manual_discount { get; set; }
        public string discount_reason { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Order Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuotationDetail> QuotationDetails { get; set; }
    }
}
