//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportDetail
    {
        public int report_detail_id { get; set; }
        public Nullable<int> report_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<int> branch_id { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<decimal> total_amount { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Product Product { get; set; }
        public virtual Report Report { get; set; }
    }
}
