//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockMovement
    {
        public int movement_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<int> warehouse_id { get; set; }
        public string movement_type { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<System.DateTime> movement_date { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> order_id { get; set; }
        public Nullable<int> lot_id { get; set; }
        public string reason { get; set; }
        public Nullable<int> purchase_order_id { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
        public virtual Warehouse Warehouse { get; set; }
        public virtual PurchaseOrder PurchaseOrder { get; set; }
    }
}
