//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierPayment
    {
        public int payment_id { get; set; }
        public int debt_id { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string payment_method { get; set; }
        public Nullable<System.DateTime> payment_date { get; set; }
        public string payment_proof { get; set; }
        public Nullable<int> user_id { get; set; }
    
        public virtual SupplierDebt SupplierDebt { get; set; }
        public virtual User User { get; set; }
    }
}
