//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierDebt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SupplierDebt()
        {
            this.SupplierPayments = new HashSet<SupplierPayment>();
        }
    
        public int debt_id { get; set; }
        public int purchase_order_id { get; set; }
        public int supplier_id { get; set; }
        public Nullable<decimal> total_amount { get; set; }
        public Nullable<decimal> paid_amount { get; set; }
        public Nullable<decimal> unpaid_amount { get; set; }
        public Nullable<System.DateTime> due_date { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        public virtual PurchaseOrder PurchaseOrder { get; set; }
        public virtual Supplier Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplierPayment> SupplierPayments { get; set; }
    }
}
