//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_AI_Customer_Analytics
    {
        public int customer_id { get; set; }
        public string customer_type { get; set; }
        public int points_balance { get; set; }
        public string masked_name { get; set; }
    }
}
