//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_AI_Master_Input_XGB
    {
        public Nullable<System.DateTime> ds { get; set; }
        public Nullable<int> branch_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<int> category_id { get; set; }
        public Nullable<int> y { get; set; }
        public Nullable<int> min_stock { get; set; }
        public int current_stock { get; set; }
        public Nullable<int> day_of_month { get; set; }
        public Nullable<int> month { get; set; }
        public Nullable<int> day_of_week { get; set; }
        public int is_weekend { get; set; }
        public int is_payday { get; set; }
        public int is_festive { get; set; }
    }
}
