//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_WeeklySales_ByProduct
    {
        public Nullable<int> branch_id { get; set; }
        public Nullable<int> category_id { get; set; }
        public int product_id { get; set; }
        public Nullable<int> SaleYear { get; set; }
        public Nullable<int> SaleWeek { get; set; }
        public Nullable<int> WeeklyQty { get; set; }
    }
}
